name: easy_rent
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  flutter_launcher_icons: ^0.9.0
  url_launcher: ^6.0.3
  fluttertoast: ^8.0.6
  flutter_swiper_null_safety: ^1.0.1
  font_awesome_flutter: ^9.0.0
  flutter_login: ^2.0.0-nullsafety.0
  flutter_easyrefresh: ^2.2.1
  bottom_navy_bar: ^6.0.0
  grpc: ^3.0.0

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  test: ^1.17.3

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/1/
    - assets/images/2/
    - assets/images/3/
    - assets/images/4/
    - assets/images/5/
    - assets/images/6/
    - assets/images/7/
    - assets/images/8/
    - assets/images/9/
    - assets/images/10/
    - assets/images/11/
    - assets/images/12/
    - assets/images/13/
    - assets/images/14/
    - assets/images/15/
    - assets/images/16/
    - assets/images/17/
    - assets/images/18/
    - assets/images/19/
    - assets/images/20/

  fonts:
    - family: SourceHanSansCN
      fonts:
        - asset: assets/fonts/SourceHanSansSC-Regular.otf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf

    - family: Vladimir
      fonts:
        - asset: assets/fonts/Vladimir.ttf

    - family: NLXJT
      fonts:
        - asset: assets/fonts/NLXJT.ttf
