[package]
name = "easy_rent_server_sdk"
version = "0.1.0"
edition = "2018"

[dependencies]
rayon = "1"
anyhow = "1"
tonic = "0.4"
prost = "0.7"
dashmap = "4"
tracing = "0.1"
serde_json = "1.0"
lazy_static = "1.4.0"
tracing-subscriber = "0.2"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tokio]
version = "1.0"
features = ["macros", "rt-multi-thread"]

[dependencies.sqlx]
version = "0.5"
features = [ "runtime-tokio-rustls", "decimal"]

[build-dependencies]
tonic-build = "0.4"
prost-build = "0.7"
