[package]
name = "easy_rent_grpc"
version = "0.1.0"
edition = "2018"


[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
tonic = "0.4"
prost = "0.7"
anyhow = "1"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
lazy_static = "1.4.0"
dashmap = "4"

[build-dependencies]
tonic-build = "0.4"
prost-build = "0.7.0"
